USE COINS;

DROP TABLE IF EXISTS Time;

CREATE TABLE `Time` (
  `Time` varchar(20) NOT NULL,
  `Accounting_Period` varchar(20) NULL,
  `Month` varchar(20) NULL
) ENGINE=BrightHouse CHARSET=utf8;

DROP TABLE IF EXISTS AccountGroup;

CREATE TABLE AccountGroup(
       Account_group_code varchar(10)  NULL,
       Name varchar(50) NULL
) ENGINE=BrightHouse CHARSET=utf8;

DROP TABLE IF EXISTS Adjustments;

CREATE TABLE Adjustments(
       Adjustment_identifier varchar(80) NULL,
       Adjustment_type varchar(80) NULL,
       Stage varchar(80) NULL,
       Title varchar(80) NULL,
       Account_code varchar(80) NULL COMMENT 'lookup',
       Account_description varchar(80) NULL,
       Line_description varchar(80) NULL,
       Department_code varchar(80) NULL COMMENT 'lookup',
       Department_description varchar(80) NULL,
       Time varchar(80) NULL COMMENT 'lookup',
       Counterparty_code varchar(80) NULL COMMENT 'lookup',
       Couterparty_description varchar(80) NULL,
       Programme_object_code varchar(80) NULL COMMENT 'lookup',
       Programme_object_description varchar(80) NULL,
       Data_type varchar(80) NULL,
       Data_type_description varchar(80) NULL,
       Accounting_Authority varchar(80) NULL,
       Accounts_capital_current varchar(80) NULL,
       Activity_code varchar(80) NULL COMMENT 'lookup',
       Budget_Boundary varchar(80) NULL,
       Budget_capital_current varchar(80) NULL,
       Resource_Capital varchar(80) NULL,
       Programme_admin varchar(80) NULL,
       CGA_Body_Type varchar(80) NULL,
       COFOG varchar(80) NULL,
       Dept_Group varchar(80) NULL,
       Estimate_line varchar(80) NULL,
       Estimate_line_last_year varchar(80) NULL,
       Estimate_line_next_year varchar(80) NULL,
       ESA varchar(80) NULL,
       Estimates_AinA varchar(80) NULL,
       Estimates_capital_current varchar(80) NULL,
       EU varchar(80) NULL,
       Income_Category varchar(80) NULL,
       LG varchar(80) NULL,
       LG_Body_Type varchar(80) NULL,
       Estimate_number varchar(80) NULL,
       Estimate_number_last_year varchar(80) NULL,
       Estimate_number_next_year varchar(80) NULL,
       NAC varchar(80) NULL,
       Near_Cash_Non_Cash varchar(80) NULL,
       NHS_Body_Type varchar(80) NULL,
       PC_Body_Type varchar(80) NULL,
       PESA varchar(80) NULL,
       PESA_1_1 varchar(80) NULL,
       PESA_AEF_Grants varchar(80) NULL,
       PESA_Capital_Support varchar(80) NULL,
       PESA_Current_Grants varchar(80) NULL,
       PESA_Delivery varchar(80) NULL,
       PESA_Non_AEF_Grants varchar(80) NULL,
       PESA_Services varchar(80) NULL,
       PESA_Tables varchar(80) NULL,
       PESA_Transfer varchar(80) NULL,
       Request_for_resources varchar(80) NULL,
       Request_for_resources_last_year varchar(80) NULL,
       Request_for_resources_next_year varchar(80) NULL,
       SBI varchar(80) NULL,
       Sector varchar(80) NULL,
       SIGNAGE varchar(80) NULL,
       Territory varchar(80) NULL,
       Cbal varchar(80) NULL,
       Grant_Provision varchar(80) NULL,
       Levy_Funded varchar(80) NULL,
       Local_Government_Use_only varchar(80) NULL,
       Net_Subhead varchar(80) NULL,
       Non_ID_Exceptions varchar(80) NULL,
       NotOCS varchar(80) NULL,
       Obal varchar(80) NULL,
       Outside_TES varchar(80) NULL,
       Pension varchar(80) NULL,
       PESA_1_1_CAP varchar(80) NULL,
       PESA_1_1_EC_Payments varchar(80) NULL,
       PESA_1_1_Local_Exp varchar(80) NULL,
       PESA_1_1_Nat_Lottery varchar(80) NULL,
       PESA_1_1_Tax_Credits varchar(80) NULL,
       PESA_1_2_NHS varchar(80) NULL,
       PESA_1_4_Locally_Financed varchar(80) NULL,
       PESA_BBC varchar(80) NULL,
       PESA_STU_LOANS varchar(80) NULL,
       Social_Fund varchar(80) NULL,
       Trust_Debt_Remuneration varchar(80) NULL,
       amount int NULL
)ENGINE = BRIGHTHOUSE
DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS Facts;

CREATE TABLE Facts(
       Data_type varchar(80) NULL COMMENT 'lookup',
       Data_type_description varchar(80) NULL,
       Department_code varchar(80) NULL COMMENT 'lookup',
       Department_description varchar(80) NULL COMMENT 'lookup',
       Account_code varchar(80) NULL COMMENT 'lookup',
       Account_description varchar(80) NULL COMMENT 'lookup',
       data_subtype varchar(80) NULL COMMENT 'lookup',
       data_subtype_description varchar(80) NULL,
       Time varchar(80) NULL COMMENT 'lookup',
       Counterparty_code varchar(80) NULL COMMENT 'lookup',
       Couterparty_description varchar(80) NULL,
       Programme_object_code varchar(80) NULL COMMENT 'lookup',
       Programme_object_description varchar(80) NULL,
       Programme_object_group_code varchar(80) NULL COMMENT 'lookup',
       Programme_object_group_description varchar(80) NULL,
       Accounting_Authority varchar(80) NULL,
       Accounts_capital_current varchar(80) NULL,
       Activity_code varchar(80) NULL,
       Budget_Boundary varchar(80) NULL,
       Budget_capital_current varchar(80) NULL,
       Resource_Capital varchar(80) NULL,
       Programme_admin varchar(80) NULL,
       CGA_Body_Type varchar(80) NULL,
       COFOG varchar(80) NULL,
       Dept_Group varchar(80) NULL,
       Estimate_line varchar(80) NULL,
       Estimate_line_last_year varchar(80) NULL,
       Estimate_line_next_year varchar(80) NULL,
       ESA varchar(80) NULL,
       Estimates_AinA varchar(80) NULL,
       Estimates_capital_current varchar(80) NULL,
       EU varchar(80) NULL,
       Income_Category varchar(80) NULL,
       LG varchar(80) NULL,
       LG_Body_Type varchar(80) NULL,
       Estimate_number varchar(80) NULL,
       Estimate_number_last_year varchar(80) NULL,
       Estimate_number_next_year varchar(80) NULL,
       NAC varchar(80) NULL,
       Near_Cash_Non_Cash varchar(80) NULL,
       NHS_Body_Type varchar(80) NULL,
       PC_Body_Type varchar(80) NULL,
       PESA varchar(80) NULL,
       PESA_1_1 varchar(80) NULL,
       PESA_AEF_Grants varchar(80) NULL,
       PESA_Capital_Support varchar(80) NULL,
       PESA_Current_Grants varchar(80) NULL,
       PESA_Delivery varchar(80) NULL,
       PESA_Non_AEF_Grants varchar(80) NULL,
       PESA_Services varchar(80) NULL,
       PESA_Tables varchar(80) NULL,
       PESA_Transfer varchar(80) NULL,
       Request_for_resources varchar(80) NULL,
       Request_for_resources_last_year varchar(80) NULL,
       Request_for_resources_next_year varchar(80) NULL,
       SBI varchar(80) NULL,
       Sector varchar(80) NULL,
       SIGNAGE varchar(80) NULL,
       Territory varchar(80) NULL,
       Cbal varchar(80) NULL,
       Grant_Provision varchar(80) NULL,
       Levy_Funded varchar(80) NULL,
       Local_Government_Use_only varchar(80) NULL,
       Net_Subhead varchar(80) NULL,
       Non_ID_Exceptions varchar(80) NULL,
       NotOCS varchar(80) NULL,
       Obal varchar(80) NULL,
       Outside_TES varchar(80) NULL,
       Pension varchar(80) NULL,
       PESA_1_1_CAP varchar(80) NULL,
       PESA_1_1_EC_Payments varchar(80) NULL,
       PESA_1_1_Local_Exp varchar(80) NULL,
       PESA_1_1_Nat_Lottery varchar(80) NULL,
       PESA_1_1_Tax_Credits varchar(80) NULL,
       PESA_1_2_NHS varchar(80) NULL,
       PESA_1_4_Locally_Financed varchar(80) NULL,
       PESA_BBC varchar(80) NULL,
       PESA_STU_LOANS varchar(80) NULL,
       Social_Fund varchar(80) NULL,
       Trust_Debt_Remuneration varchar(80) NULL,
       Value int NULL
) ENGINE = BRIGHTHOUSE
DEFAULT CHARSET=utf8;

